-- 코드를 입력하세요
SELECT USER_GOOD.USER_ID, USER_GOOD.NICKNAME, CONCAT(USER_GOOD.CITY,' ' , USER_GOOD.STREET_ADDRESS1 ,' ', USER_GOOD.STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTRING(USER_GOOD.TLNO, 1, 3),'-',SUBSTRING(USER_GOOD.TLNO, 4, 4),'-', SUBSTRING(USER_GOOD.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER AS USER_GOOD
INNER JOIN USED_GOODS_BOARD AS USER_BOARD
ON USER_GOOD.USER_ID = USER_BOARD.WRITER_ID
GROUP BY USER_GOOD.USER_ID
HAVING COUNT(*) >= 3
ORDER BY USER_GOOD.USER_ID DESC;