-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AS AO
LEFT JOIN ANIMAL_INS AS AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.NAME IS NULL AND AO.NAME IS NOT NULL
ORDER BY AO.ANIMAL_ID;

# SELECT *
# FROM ANIMAL_OUTS AS AO
# LEFT JOIN ANIMAL_INS AS AI 
# ON AI.ANIMAL_ID = AO.ANIMAL_ID;