-- 코드를 입력하세요
SELECT M.MEMBER_ID, M.MEMBER_NAME, M.GENDER, DATE_FORMAT(M.DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE AS M
WHERE M.DATE_OF_BIRTH LIKE '_____03%' AND M.TLNO IS NOT NULL AND M.GENDER = 'W'
ORDER BY M.MEMBER_ID; 