-- 코드를 입력하세요
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS C, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CR
WHERE C.CAR_ID = CR.CAR_ID AND C.CAR_TYPE = '세단' AND CR.START_DATE LIKE '_____10%'
ORDER BY CAR_ID DESC;