-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", UF.BOARD_ID, '/', UF.FILE_ID, UF.FILE_NAME, UF.FILE_EXT) AS 'FILE_PATH'
FROM USED_GOODS_FILE AS UF
INNER JOIN USED_GOODS_BOARD AS UG ON UF.BOARD_ID = UG.BOARD_ID
WHERE UG.VIEWS = (SELECT MAX(UG.VIEWS)
                   FROM USED_GOODS_BOARD AS UG)
ORDER BY UF.FILE_ID DESC;